[package]
name = "lldb_remote_ext"
version = "0.0.2"
edition = "2024"
license = "MIT-0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zed_extension_api = "0.7"
